# src/ApiBundle/Resources/config/doctrine/Tag.orm.yml
ApiBundle\Entity\Tag:
    type: entity
    table: tag
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        updated:
            type: string
            length: 255
        deleted:
            type: integer
            length: 1